### PR TITLE
Season 2023-2 January 2024 Update

### PR DESCRIPTION
**Pull request by EstebanMz**
- **[Dust Shot](https://www.revoltworld.net/dl/dust-shot/) has been recategorized from Amateur to Advanced class.** After it was [discussed with TTDriver](https://discord.com/channels/308469225557721090/500502859146854401/1195806440858865805), its author, that his car was too good for Amateur, he agreed to move it to Advanced, with a Top Speed buff of +0.5mph and an adjustment to its weapon offset.
- Outraga is replacing Starway as the former is much better balanced for Amateur class.
- The following changes has been done to keep the same amount of cars per category, after the recategorization of Dust Shot: **[Pegmound](https://www.revoltworld.net/dl/pegmound/) (Advanced) has been removed from the pack** (it's one of the least used car in the pack and it's also a rally car) and **[Smokie](https://www.revoltworld.net/dl/smokie/) (Amateur) has been added into the pack** (between a [list of 14 suggestions](https://discord.com/channels/308469225557721090/500502859146854401/1195931154470162453) to fill this spot, Smokie turned out to be the best of them).
_Linked messages can only be seen by Staff members._

_TL;DR_
**Amateur:**
(IN) Smokie
(IN) Outraga
(OUT) Starway
(OUT) Dust Shot

**Advanced:**
(IN) Dust Shot
(OUT) Pegmound

### CODE REVIEW

**Comment by EstebanMz** [comment]
I may change my opinion about adding Smokie, it needs further testing, also, Starway might get replaced for being too good, I'll see if I can find a replacement as well.

**Review by BGMP — CHANGES_REQUESTED** [review]
I tried Smokie for the new IO update and it feels quite broken. I personally think it should be reconsidered if it hasn't been tested yet.

**Comment by EstebanMz** [comment]
> I tried Smokie for the new IO update and it feels quite broken. I personally think it should be reconsidered if it hasn't been tested yet.

It's been already tested [earlier this week](https://online.re-volt.io/sessions/results.php?file=main/session_2024-01-22_17-30-05.csv)! The conclusion is that the car is only broken for real when the lobby is half full and the tracks being raced are mostly flat and wide, the moment Smokie faces more difficulty it's performance drops drastically, hence it becomes in a balanced car for Amateur.

**Review by BGMP — APPROVED** [review]
OK... I guess with 0.7-0.8 it could work. I'll trust you here guys

**Pull request merged**
